server:
  port: 8080
  servlet:
    context-path: /auth
spring:
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML5
    encoding: UTF-8
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:3306/oauth?useUnicode=true&characterEncoding=utf8
    username: root
    password: 123456