spring:
    datasource:
        hikari:
            connection-test-query: SELECT 1 FROM DUAL
            minimum-idle: 1
            maximum-pool-size: 5
        driver-class-name: com.mysql.jdbc.Driver
        jdbc-url:
        username:
        password:
        initialization-mode: always
    jpa:
      hibernate:
        ddl-auto: none
# --- server
server:
  port: 8080
security:
  oauth2:
    authorization:
      check-token-access: true

